spring.application.name=almora

spring.data.mongodb.uri=mongodb+srv://andrea:andrea123@cluster0.rnxsdeo.mongodb.net/almora_db


server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

